[env:lkshield]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
monitor_speed = 115200

lib_extra_dirs =
    C:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared

build_flags =
    -IC:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared
    -IC:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared/hal
    -IC:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared/drivers
    -IC:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared/common
    -I./
    -DDEVICE_ID=0x11
    -DDEVICE_TYPE=0x11