name=shennong-sensors
version=1.0.0
author=
maintainer=
sentence=Sensor drivers
paragraph=
category=Sensors
url=
architectures=*
includes=dht22.h,bh1750.h,ph_sensor.h,ds18b20.h,sgp30.h,tds.h,ultrasonic.h,hx711.h,infrared_level.h
