[env:lkshield]
platform = ststm32@12.1.1
board = genericSTM32F103C8
framework = stm32cube
monitor_speed = 115200

lib_ldf_mode = chain+
lib_extra_dirs =
    C:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared/common
    C:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared/hal
    C:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared/drivers/sensor
    C:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared/drivers/actuator

build_flags =
    -I./src
    -IC:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared
    -IC:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared/hal
    -IC:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared/drivers
    -IC:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared/drivers/sensor
    -IC:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared/drivers/actuator
    -IC:/Users/Administrator/Documents/项目设计/坎川工业/shennong-platform/shared/common
    -DDEVICE_ID=0x01
    -DDEVICE_TYPE=0x01
    -DUSE_HAL_DRIVER
    -DSTM32F103xB
